# Miyabi Autonomous System Configuration
# Master configuration for the complete autonomous agent system

version: "1.0"

# System identity
system:
  name: "Brand Builder Miyabi"
  version: "1.0.0"
  mode: "autonomous"  # autonomous | supervised | manual
  guardian: "hiromima"

# Agent registry
agents:
  # Support Agents (Autonomous Operations)
  support:
    - name: "CostMonitoringAgent"
      enabled: true
      priority: 1  # Highest priority
      check_interval: 3600  # 1 hour
      capabilities:
        - "billing_monitoring"
        - "cost_projection"
        - "circuit_breaker"

    - name: "IncidentCommanderAgent"
      enabled: true
      priority: 1
      capabilities:
        - "incident_detection"
        - "root_cause_analysis"
        - "automatic_rollback"
        - "human_escalation"

    - name: "SystemRegistryAgent"
      enabled: true
      priority: 2
      capabilities:
        - "agent_onboarding"
        - "compliance_testing"
        - "agent_registration"

    - name: "AuditAgent"
      enabled: true
      priority: 2
      check_interval: 86400  # 24 hours
      capabilities:
        - "security_audit"
        - "access_log_analysis"
        - "anomaly_detection"

    - name: "CoordinatorAgent"
      enabled: true
      priority: 3
      capabilities:
        - "task_routing"
        - "agent_orchestration"
        - "workflow_management"

  # Core Agents (Brand Building)
  core:
    - name: "StructureAgent"
      enabled: true
      capabilities:
        - "estack_mapping"
        - "rsi_protocol"
        - "hearing_sheet_processing"

    - name: "ExpressionAgent"
      enabled: true
      capabilities:
        - "expression_generation"
        - "creative_branching"

    - name: "EvaluationAgent"
      enabled: true
      capabilities:
        - "multi_model_evaluation"
        - "auto_improvement"
        - "quality_scoring"

    - name: "CopyAgent"
      enabled: true
      capabilities:
        - "tone_design"
        - "core_message_generation"
        - "tagline_generation"

    - name: "LogoAgent"
      enabled: true
      capabilities:
        - "iaf_engine"
        - "symbol_analysis"
        - "logo_concept"

    - name: "VisualAgent"
      enabled: true
      capabilities:
        - "vi_system_design"
        - "visual_guidelines"
        - "identity_system"

# Autonomy rules
autonomy:
  # The Three Laws of Autonomy
  laws:
    objectivity:
      enabled: true
      description: "All decisions based on observable data and defined rules"

    self_sufficiency:
      enabled: true
      description: "Minimize human intervention"
      incident_threshold: 3  # Max incidents before system review

    traceability:
      enabled: true
      description: "All actions recorded on GitHub"
      require_github_trail: true

  # Zero-human approval
  auto_approval:
    enabled: true
    quality_threshold: 90  # Score >= 90 for auto-approval
    max_improvement_attempts: 3

  # Graceful degradation
  degradation:
    enabled: true
    rollback_attempts: 3
    escalation_on_failure: true

# GitHub integration
github:
  repository: "hiromima/Brand-Builder"
  default_branch: "main"

  labels:
    priority:
      - "P0-Critical"
      - "P1-High"
      - "P2-Medium"
      - "P3-Low"

    status:
      - "human-intervention-required"
      - "auto-approved"
      - "in-review"
      - "blocked"

    type:
      - "incident"
      - "cost-alert"
      - "security-alert"
      - "enhancement"
      - "bug"

  issue_templates:
    enabled: true
    path: ".github/ISSUE_TEMPLATE"

  workflows:
    path: ".github/workflows"
    required:
      - "economic-circuit-breaker.yml"
      - "agent-onboarding.yml"
      - "incident-response.yml"
      - "quality-gate.yml"

# Knowledge management
knowledge:
  vector_db:
    type: "chroma"
    url: "http://localhost:8000"
    collection: "brand-knowledge"

  graph_db:
    type: "neo4j"
    uri: "neo4j+s://c74787d1.databases.neo4j.io"
    database: "neo4j"

  update_interval: 604800  # Weekly (in seconds)

# Security
security:
  secrets_manager:
    type: "github_secrets"  # Future: "hashicorp_vault"
    rotation_interval: 2592000  # 30 days

  audit_log:
    enabled: true
    path: ".miyabi/logs/audit.log"
    retention_days: 365

  anomaly_detection:
    enabled: true
    alert_on_unusual_activity: true

# Logging
logging:
  level: "INFO"  # DEBUG | INFO | WARN | ERROR
  directory: ".miyabi/logs"
  rotation:
    max_size: "10MB"
    max_files: 10

  destinations:
    - type: "file"
      path: ".miyabi/logs/miyabi.log"
    - type: "github_discussion"
      category: "System Logs"
      level: "WARN"  # Only WARN and ERROR to GitHub

# Monitoring
monitoring:
  health_check_interval: 300  # 5 minutes
  metrics:
    - "api_latency"
    - "error_rate"
    - "cost_per_operation"
    - "quality_score"
    - "human_intervention_rate"

  alerts:
    error_rate_threshold: 0.05  # 5%
    latency_threshold: 30000  # 30 seconds

# Disaster recovery
disaster_recovery:
  backup:
    enabled: true
    interval: 86400  # Daily
    destination: ".miyabi/backups"
    retain_days: 30

  restore:
    enabled: true
    source: ".miyabi/backups"

# Meta-operations
meta:
  self_improvement:
    enabled: true
    review_interval: 604800  # Weekly
    propose_changes: true

  system_evolution:
    enabled: true
    allow_rule_proposals: true
    require_guardian_approval: true
