name: Quality Scoring Check

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      threshold:
        description: 'Quality score threshold (80 or 90)'
        required: false
        default: '90'

jobs:
  quality-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Quality Scoring Tests
        id: quality
        run: node scripts/test_quality_scoring.js
        env:
          QUALITY_THRESHOLD: ${{ github.event.inputs.threshold || '90' }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Comment PR with results
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const comment = `## Quality Scoring Results

            ✅ All quality scoring tests passed!

            - EvaluationAgent Integration: PASS
            - MultiModelEvaluator Integration: PASS
            - Score Threshold Validation (80, 90): PASS
            - GitHub Actions Compatibility: PASS

            **Threshold**: ${process.env.QUALITY_THRESHOLD || '90'} points

            See workflow run for detailed results.`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
